spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/hexagonal
    username: AmirTest
    password: 1234
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.sql: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE